name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Hugo build
      run: hugo --minify

    - name: Upload build result
      # No need to upload if we won't deploy.
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: public

  deploy-to-object-storage:
    name: Deploy to Object Storage
    runs-on: ubuntu-latest
    needs: build
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    # References to the env context aren't supported here, so copy-paste from
    # the upload step.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Download build result
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: public

    - name: Generate HTML
      run: |
        echo '<html>hello6</html>' > index.html
        cat index.html

    - name: Upload Static Website
      uses: oracle-actions/run-oci-cli-command@v1.1.1
      with:
        command: '--debug os object put --namespace ${{ secrets.OCI_CLI_NAMESPACE }} -bn website --file index.html --content-type text/html --force'
        silent: false
